### ISSUE TITLE
Access to the path '/app/data/spam-ham.txt' is denied.

### ISSUE THREAD

**Issue by seventhsite** [TiraelSedai/ClubDoorman#4]
Ошибка при запуске контейнера:

```
antispam  | Unhandled exception. System.UnauthorizedAccessException: Access to the path '/app/data/spam-ham.txt' is denied.
antispam  |  ---> System.IO.IOException: Permission denied
antispam  |    --- End of inner exception stack trace ---
antispam  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
antispam  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
antispam  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
antispam  |    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
antispam  |    at ClubDoorman.Program.InitData() in /src/Program.cs:line 48
antispam  |    at ClubDoorman.Program.Main(String[] args) in /src/Program.cs:line 10
antispam  |    at ClubDoorman.Program.<Main>(String[] args)
```

**Comment by seventhsite** [comment]
Решается `chown -R 1654:9376 data/`

**Comment by TiraelSedai** [comment]
@seventhsite можешь сделать PR? я так понимаю что это chown -R app:app /data который надо делать сразу после mkdir

**Comment by seventhsite** [comment]
А пользователь вообще для чего-то нужен? Попробовал совсем без него - работает.

**Comment by TiraelSedai** [comment]
Пользователь нужен чтобы приложение не бегало под рутом.

Ладно, я как-нибудь как выдастся свободное время покопаюсь, вроде бы и со старой конфигурацией у других людей работало, надо разобраться в чём дело
